.fvm/fvm_config.json
pubspec.lock
pubspec.yaml

- bump Flutter/Dart to 3.13.6/3.1.3
- なし

build: bump Flutter/Dart to 3.13.6/3.1.3

---

.github/CODEOWNERS
.github/actions/setup_flutter/action.yml
.github/dependabot.yml
.github/labeler.yml
.github/pull_request_template.md
.github/workflows/assign-author-to-pr.yaml
.github/workflows/code-check.yml
.github/workflows/lint-github-actions-workflows.yaml
.github/workflows/pull-request-labeler.yml
.vscode/settings.json
melos.yaml
pubspec.lock
pubspec.yaml

- Translate comments in the VS Code configuration file
- Add sdkPath to the VS Code configuration
- When running `pub get` in the root's` pubspec.yaml`, it wasn't looking at the dart from `fvm`, so I specified it
- Add melos command
- Add GitHub Actions workflows
- None

ci/cd: Add melos command and actions

---

.vscode/settings.json
packages/flutterfire_authenticator/.gitignore
packages/flutterfire_authenticator/.metadata
packages/flutterfire_authenticator/CHANGELOG.md
packages/flutterfire_authenticator/README.md
packages/flutterfire_authenticator/analysis_options.yaml
packages/flutterfire_authenticator/lib/authenticator.dart
packages/flutterfire_authenticator/lib/src/apple_authenticator.dart
packages/flutterfire_authenticator/lib/src/auth_exception.dart
packages/flutterfire_authenticator/lib/src/authenticatable.dart
packages/flutterfire_authenticator/lib/src/authenticator.dart
packages/flutterfire_authenticator/lib/src/google_authenticator.dart
packages/flutterfire_authenticator/lib/src/phone_authenticator.dart
packages/flutterfire_authenticator/lib/src/signing_method.dart
packages/flutterfire_authenticator/lib/src/user_extension.dart
packages/flutterfire_authenticator/pubspec.yaml
packages/flutterfire_authenticator/test/authenticator_test.dart
pubspec.lock
pubspec.yaml

add flutterfire_authenticator

---

packages/flutterfire_authenticator/lib/src/auth_exception.dart
packages/flutterfire_authenticator/lib/src/authenticator.dart
packages/flutterfire_authenticator/test/src/auth_exception_test.dart

- Expose FirebaseAuth.currentUser
- Rename AuthException clases
- Rename fetchJsonWebToken to fetchJwt

feat: publish Authenticator.user

---

packages/flutterfire_remote_parameter_fetcher/.gitignore
packages/flutterfire_remote_parameter_fetcher/.metadata
packages/flutterfire_remote_parameter_fetcher/CHANGELOG.md
packages/flutterfire_remote_parameter_fetcher/README.md
packages/flutterfire_remote_parameter_fetcher/analysis_options.yaml
packages/flutterfire_remote_parameter_fetcher/lib/remote_parameter_fetcher.dart
packages/flutterfire_remote_parameter_fetcher/lib/src/remote_parameter_fetcher.dart
packages/flutterfire_remote_parameter_fetcher/pubspec.yaml
packages/flutterfire_remote_parameter_fetcher/test/data_class.dart
packages/flutterfire_remote_parameter_fetcher/test/src/remote_parameter_fetcher_test.dart

feat: add flutterfire_remote_parameter_featcher

---

.cspell/flutter-words.txt
packages/flutterfire_tracker/.gitignore
packages/flutterfire_tracker/.metadata
packages/flutterfire_tracker/CHANGELOG.md
packages/flutterfire_tracker/README.md
packages/flutterfire_tracker/analysis_options.yaml
packages/flutterfire_tracker/lib/src/trackable.dart
packages/flutterfire_tracker/lib/src/tracker.dart
packages/flutterfire_tracker/lib/tracker.dart
packages/flutterfire_tracker/pubspec.yaml
packages/flutterfire_tracker/test/src/tracker_test.dart

feat: add flutterfire_tracker

---

packages/flutterfire_authenticator/lib/authenticator.dart
packages/flutterfire_authenticator/lib/src/user_extension.dart

- Publish Firebase Auth User
I made it public because there are cases where I want to specify the type and retrieve it using Provider or similar methods.

feat: Publish Firebase Auth User

---

packages/flutterfire_authenticator/lib/src/authenticator.dart

- Add useEmulator method to Authenticator
- None

feat: Add useEmulator method to Authenticator

---

packages/altfire_configurator/example/lib/main.dart
packages/altfire_configurator/lib/altfire_configurator.dart
packages/altfire_configurator/lib/configurator.dart
packages/altfire_configurator/pubspec.yaml
packages/altfire_configurator/test/src/configurator_test.dart
packages/altfire_lints_test/test/lints/dispose_config.dart

#29 
- Renamed `configurator` to match package name `altfire_configurator`
- Add false secrets to ignore list
- Publish.
```
$ melos exec
└> dart pub publish --dry-run
└> SUCCESS
```
Reference:
- https://github.com/firebase/flutterfire/blob/master/packages/firebase_auth/firebase_auth/pubspec.yaml

chore: Preparing to Publish Altfire Configurator on pub.dev

---

.github/CODEOWNERS

- update CODEOWNERS to include @altive/flutter

docs: update CODEOWNERS to include @altive/flutter

---

packages/altfire_authenticator/pubspec.yaml
packages/altfire_configurator/pubspec.yaml
packages/altfire_messenger/pubspec.yaml
packages/altfire_tracker/pubspec.yaml

- add homepage
- add repository
- add issue_tracker
- add description
> Add more detail to the description field of pubspec.yaml. Use 60 to 180 characters to describe the package, what it does, and its target use case.

chore: update package descriptions

---

packages/altfire_lints/README.md

#38
- Update README.
- For some reason --no-dry-run was the first time it was pointed out to me.

docs(altfire_lints): add README

---

melos.yaml
packages/altfire_configurator/example/pubspec.lock
packages/altfire_messenger/lib/messenger.dart

- Fix "export ordering"
- Fix melos run analye

fix: If melos run analyze fails, it will still be a success.

---

melos.yaml
packages/altfire_tracker/pubspec.yaml

closes #59 
Update firebase_crashlytics: ^3.4.9

feat: Update firebase_crashlytics

---

packages/altfire_tracker/lib/altfire_tracker.dart

closes #64 
Export MethodChannelFirebaseCrashlytics

feat: Export MethodChannelFirebaseCrashlytics

---

packages/altfire_authenticator/README.md
packages/altfire_messenger/README.md

docs: add README

---

packages/altfire_authenticator/CHANGELOG.md
packages/altfire_authenticator/pubspec.yaml

- altfire_authenticator@0.1.1
- melos version --scope=altfire_authenticator

chore(release): publish packages

---

example/pubspec.lock
packages/altfire_authenticator/example/pubspec.lock
packages/altfire_authenticator/pubspec.yaml

- Add false_secrets
```
> melos publish --dry-run
~
* 41 potential leaks detected in 4 files:
- /example/android/app/google-services.json
- /example/ios/Runner/GoogleService-Info.plist
- /example/lib/firebase_options.dart
- /example/macos/Runner/GoogleService-Info.plist
Add git-ignore style patterns to `false_secrets` in `pubspec.yaml`
to ignore this. See https://dart.dev/go/false-secrets
Sorry, your package is missing some requirements and can't be published yet.
For more information, see: https://dart.dev/tools/pub/cmd/pub-lish.
```

chore(authenticator): Add false_secrets

---

.vscode/extensions.json

- We removed those that were slow to upgrade (MELOS) and those that seemed to have different tastes.

chore: Remove unused VS Code extensions

---

README.md
example/pubspec.lock
packages/altfire_authenticator/example/pubspec.lock
packages/altfire_configurator/example/pubspec.lock
packages/altfire_messenger/example/pubspec.lock
packages/altfire_tracker/example/pubspec.lock

- Update the dependency packages of example
I committed because there was a difference when I ran `melos bs` on the latest `main`. 
It seems better to do `melos bs` together with `melos version`.

chore: Update the dependency packages of example

---

.github/dependabot.yml
melos.yaml

- Improve dependabot schedules
- Remove firebase dependencies from Melos.command

ci: Improve dependabot schedules

---

packages/altfire_authenticator/lib/src/authenticator.dart

None.
- Publish the function to revoke the Apple user token
- None.

feat(authenticator): Publish the function to revoke the Apple user token

---

.github/dependabot.yml
example/ios/Podfile.lock
example/macos/Podfile.lock
packages/altfire_authenticator/example/ios/Podfile.lock
packages/altfire_authenticator/example/macos/Podfile.lock
packages/altfire_authenticator/example/pubspec.yaml
packages/altfire_authenticator/pubspec.yaml
packages/altfire_configurator/example/ios/Podfile.lock
packages/altfire_configurator/example/macos/Podfile.lock
packages/altfire_configurator/example/pubspec.yaml
packages/altfire_configurator/pubspec.yaml
packages/altfire_messenger/example/ios/Podfile.lock
packages/altfire_messenger/example/macos/Podfile.lock
packages/altfire_messenger/example/pubspec.yaml
packages/altfire_messenger/pubspec.yaml
packages/altfire_tracker/example/ios/Podfile.lock
packages/altfire_tracker/example/macos/Podfile.lock
packages/altfire_tracker/example/pubspec.yaml
packages/altfire_tracker/pubspec.yaml

None.
- Update a dependency to the latest release
None.
Dependabot hasn't been active for about two weeks, so I manually updated the dependency packages! 
The group specification might be the cause, so I tried removing the group specification in `dependabot.yaml`.

build: Update a dependency to the latest release

---

packages/altfire_messenger/lib/altfire_messenger.dart
packages/altfire_messenger/lib/src/messenger.dart
packages/altfire_messenger/pubspec.yaml
packages/altfire_messenger/test/src/messenger_test.dart

None.
- Add a set of methods to receive remote notifications
None.
I confirmed the operation of the added methods in the application where they were used.
I added them because they are necessary for addressing [this issue](https://github.com/Favosia/favosia_flutter/issues/1713).

feat: Add a set of methods to receive notifications
